export const GREETINGS = [
  "chào",
  "xin chào",
  "chào bạn",
  "chào anh",
  "chào chị",
  "chào em",
  "chào bác sĩ",
  "chào hệ thống",
  "chào mọi người",
  "chào buổi sáng",
  "chào buổi trưa",
  "chào buổi tối",
  "xin chào bạn",
  "mình chào bạn",
  "rất vui được gặp bạn",
  "hello",
  "hi",
];
export const THANKS_KEYWORDS = [
  "cảm ơn",
  "xin cảm ơn",
  "cảm ơn bạn",
  "cảm ơn anh",
  "cảm ơn chị",
  "cảm ơn em",
  "cảm ơn bác sĩ",
  "cảm ơn hệ thống",
  "cảm ơn mọi người",
  "chân thành cảm ơn",
  "rất cảm ơn",
  "cảm ơn nhiều",
  "cảm ơn rất nhiều",
  "tôi cảm ơn bạn",
  "biết ơn",
];

export const MEDICAL_KEYWORDS = [
  // Triệu chứng
  "đau đầu",
  "đau bụng",
  "sốt",
  "ho",
  "cảm",
  "cúm",
  "mệt mỏi",
  "chóng mặt",
  "buồn nôn",
  "nôn",
  "tiêu chảy",
  "táo bón",
  "dị ứng",
  "phát ban",
  "khó thở",
  "đau ngực",
  "tim đập nhanh",
  "sưng tấy",
  "mất ngủ",
  "tiểu buốt",
  "ra máu",

  // Bệnh lý
  "bệnh",
  "bệnh lý",
  "tiểu đường",
  "huyết áp cao",
  "tim mạch",
  "hen suyễn",
  "viêm phổi",
  "viêm gan",
  "ung thư",
  "HIV",
  "COVID",

  // Khám và chẩn đoán
  "triệu chứng",
  "khám",
  "chẩn đoán",
  "xét nghiệm",
  "siêu âm",
  "nội soi",
  "X-quang",
  "MRI",
  "CT Scan",
  "sinh thiết",

  // Thuốc và điều trị
  "thuốc",
  "điều trị",
  "chữa bệnh",
  "kháng sinh",
  "đơn thuốc",
  "toa thuốc",
  "phẫu thuật",
  "truyền dịch",
  "hóa trị",
  "tiêm chủng",
  "vaccine",
  "phản ứng phụ",
  "chống chỉ định",
  "dược",
  "đông y",
  "tây y",

  // Nhân sự và cơ sở y tế
  "bác sĩ",
  "y tá",
  "y tế",
  "phòng khám",
  "bệnh viện",
  "trung tâm y tế",
  "khoa nội",
  "khoa ngoại",
  "khoa nhi",
  "khoa sản",
  "bác sĩ gia đình",
  "chuyên khoa",
  "chuyên gia",

  // Dịch vụ và thủ tục
  "đặt lịch khám",
  "lấy số thứ tự",
  "tư vấn sức khỏe",
  "giấy khám sức khỏe",
  "giấy nghỉ ốm",
  "chuyển viện",
  "dịch vụ y tế tại nhà",
  "đăng ký khám bệnh",
  "cấp cứu",
  "cấp cứu 115",

  // Bảo hiểm và chi phí
  "bảo hiểm y tế",
  "thẻ BHYT",
  "bảo hiểm tư nhân",
  "viện phí",
  "chi phí khám",
  "hóa đơn bệnh viện",
  "thanh toán",

  // Sức khỏe và phòng ngừa
  "sức khỏe",
  "kiểm tra định kỳ",
  "phòng bệnh",
  "dinh dưỡng",
  "tập thể dục",
  "sức khỏe tinh thần",
  "chăm sóc thai kỳ",
  "vệ sinh cá nhân",
    "lối sống lành mạnh",
  "đau lưng",
  "đau khớp",
  "đau vai gáy",
  "tê bì",
  "co giật",
  "nổi mẩn",
  "ngứa",
  "khô da",
  "rụng tóc",
  "sưng hạch",
  "chán ăn",
  "sụt cân",
  "tăng cân",
  "khó nuốt",
  "ợ hơi",
  "ợ chua",
  "đầy bụng",
  "tiểu nhiều",
  "khát nước",
  "nhìn mờ",
  "ù tai",
  "chảy máu cam",
  "đau răng",
  "sưng lợi",
  "hôi miệng",
  "khàn tiếng",
  "mất tiếng",
  "sổ mũi",
  "ngạt mũi",
  "hắt hơi",
  "nhức mắt",
  "đỏ mắt",
  "chảy nước mắt",
  "sợ ánh sáng",
  "tức ngực",
  "khó thở khi nằm",
  "phù chân",
  "chuột rút",
  "suy giảm trí nhớ",
  "mất tập trung",
  "lo âu",
  "trầm cảm",
  "rối loạn giấc ngủ",
  "tiểu không tự chủ",
  "tiểu ra máu",
  "tiểu rắt",
  "đau bụng dưới",
  "chu kỳ kinh nguyệt bất thường",
  "tiết dịch âm đạo",
  "đau tinh hoàn",
  "nổi cục",
  "khối u",
  "vết loét",
  "thay đổi màu da",
  "vàng da",
  "vàng mắt",
  "phân bạc màu",
  "tiểu sẫm màu",
  "da khô",
  "lưỡi đau",
  "móng giòn",
  "run tay",
  "vã mồ hôi",
  "hồi hộp",
  "yếu cơ",
  "co cứng",
  "đi lại khó khăn",
  "rối loạn thăng bằng",
  "nói khó",
  "nuốt khó",
  "liệt mặt",
  "méo miệng",
  "chóng mặt xoay tròn",
  "giảm thính lực",
  "chảy mủ tai",
  "chảy máu chân răng",
  "nổi mụn",
  "sẹo",
  "rạn da",
  "nổi gân xanh",
  "tê ngón tay",
  "đau cổ",
  "đau vai",
  "khó xoay cổ",
  "cứng khớp",
  "kêu lạo xạo khớp",
  "giảm biên độ khớp",
  "teo cơ",
  "đau dọc xương sườn",
  "khó tiêu",
  "nóng rát thượng vị",
  "trướng bụng",
  "ợ nóng",
  "suy giảm thị lực",
  "song thị",
  "sụp mi",
  "lồi mắt",
  "khô mắt",
  "chảy nước mắt sống",
  "chói mắt",
  "giảm khứu giác",
  "mất vị giác",
  "nuốt vướng",
  "viêm loét miệng",
  "lở miệng",
  "nổi mụn nước",
  "ban đỏ",
  "mụn mủ",
  "vảy nến",
  "chàm",
  "mề đay",
  "nốt ruồi thay đổi",
  "vết bớt",
  "tóc bạc sớm",
  "tóc khô xơ",
  "móng tay đổi màu",
  "móng chân dày",
  "nấm móng",
  "hôi chân",
  "nứt gót chân",
  "chai chân",
  "mắt cá chân",
  "bầm tím không rõ nguyên nhân",
  "sưng hạch bạch huyết",
  "đổ mồ hôi đêm",
  "sút cân không rõ nguyên nhân",
  "sưng tuyến giáp",
  "cổ to",
  "khó thở khi nằm",
  "khò khè",
  "thở rít",
  "ho có đờm",
  "ho ra máu",
  "đau rát họng",
  "vướng họng",
  "nghẹt mũi một bên",
  "chảy mũi sau",
  "đau xoang",
  "ngứa mũi",
  "khịt mũi",
  "chảy nước mũi trong",
  "chảy nước mũi vàng",
  "chảy nước mũi xanh",
  "mất khứu giác tạm thời",
  "khó thở bằng mũi",
  "đau sau nhãn cầu",
  "mắt khô rát",
  "cộm mắt",
  "nhức mỏi mắt",
  "nổi hạt ở mí mắt",
  "chắp lẹo",
  "viêm kết mạc",
  "đau tai",
  "ù tai",
  "chảy dịch tai",
  "giảm thính lực một bên",
  "nghe kém",
  "chóng mặt tiền đình",
  "nôn ói do chóng mặt",
  "mất thăng bằng",
  "run chân tay",
  "đứng không vững",
  "đi lại xiêu vẹo",
  "yếu một bên cơ thể",
  "khó nói",
  "nói lắp",
  "nuốt sặc",
  "méo mặt",
  "lệch mặt",
  "sụp mí mắt",
  "nhìn đôi",
  "khó mở miệng",
  "đau hàm",
  "khớp hàm kêu",
  "sưng quai hàm",
  "đau vùng thái dương",
  "đau đầu kèm sốt",
  "cứng gáy",
  "sợ ánh sáng",
  "sợ tiếng ồn",
  "tê nửa người",
  "rối loạn cảm giác",
  "kim châm",
  "kiến bò",
  "chuột rút",
  "co thắt cơ",
  "yếu cơ",
  "teo cơ",
  "run rẩy",
  "giật cơ",
  "khó đi lại",
  "đau dọc đường đi dây thần kinh",
  "đau dây thần kinh tọa",
  "đau thần kinh liên sườn",
  "đau thần kinh số V",
  "liệt mặt ngoại biên",
  "rối loạn tiểu tiện",
  "tiểu són",
  "tiểu không tự chủ",
  "tiểu đêm",
  "tiểu nhiều lần",
  "bí tiểu",
  "đau khi quan hệ",
  "giảm ham muốn",
  "rối loạn cương dương",
  "xuất tinh sớm",
  "khô âm đạo",
  "ngứa vùng kín",
  "nổi mụn rộp sinh dục",
  "chảy dịch bất thường",
  "đau bụng kinh",
  "kinh nguyệt không đều",
  "rong kinh",
  "vô kinh",
  "đau vú",
  "nổi cục ở vú",
  "tiết dịch núm vú",
  "tăng nhạy cảm vú",
  "đau hậu môn",
  "chảy máu hậu môn",
  "ngứa hậu môn",
  "sa trực tràng",
  "nứt kẽ hậu môn",
  "polyp hậu môn",
  "trĩ ngoại",
  "trĩ nội",
  "tiêu phân đen",
  "tiêu phân có máu",
  "tiêu phân nhầy",
  "tiêu phân sống",
  "tiêu chảy mãn tính",
  "tiêu chảy cấp tính",
  "khó tiêu",
  "chướng bụng sau ăn",
  "nặng bụng",
  "rối loạn tiêu hóa",
  "viêm đại tràng",
  "hội chứng ruột kích thích",
  "viêm loét đại tràng",
  "bệnh Crohn",
  "trào ngược dạ dày",
  "viêm dạ dày",
  "loét dạ dày",
  "polyp dạ dày",
  "viêm ruột thừa",
  "sỏi mật",
  "viêm túi mật",
  "viêm tụy",
  "suy gan",
  "xơ gan",
  "ung thư gan",
  "viêm đường tiết niệu",
  "viêm bàng quang",
  "sỏi thận",
  "suy thận",
  "viêm cầu thận",
  "ung thư thận",
  "phì đại tiền liệt tuyến",
  "ung thư tiền liệt tuyến",
  "viêm tinh hoàn",
  "viêm mào tinh hoàn",
  "ung thư tinh hoàn",
  "ung thư bàng quang",
  "ung thư trực tràng",
  "ung thư ruột kết",
  "ung thư dạ dày",
  "ung thư thực quản",
  "ung thư phổi",
  "ung thư vú",
  "ung thư cổ tử cung",
  "ung thư buồng trứng",
  "ung thư tuyến giáp",
  "ung thư máu",
  "bạch cầu cấp",
  "bạch cầu mãn",
  "đa u tủy",
  "ung thư hạch",
  "Lupus ban đỏ",
  "viêm khớp dạng thấp",
  "xơ cứng bì",
  "bệnh vẩy nến",
  "bệnh bạch biến",
  "Zona thần kinh",
  "giời leo",
  "thủy đậu",
  "sởi",
  "quai bị",
  "rubella",
  "sốt xuất huyết",
  "tay chân miệng",
  "sốt rét",
  "viêm não",
  "viêm màng não",
  "động kinh",
  "Parkinson",
  "Alzheimer",
  "tai biến mạch máu não",
  "đột quỵ",
  "nhồi máu cơ tim",
  "suy tim",
  "hẹp van tim",
  "hở van tim",
  "rối loạn nhịp tim",
  "cao huyết áp",
  "huyết áp thấp",
  "rối loạn mỡ máu",
  "xơ vữa động mạch",
  "suy giãn tĩnh mạch",
  "tắc mạch máu",
  "thiếu máu não",
  "thiếu máu cơ tim",
  "bệnh mạch vành",
  "tiểu đường thai kỳ",
  "tiền tiểu đường",
  "hạ đường huyết",
  "tăng đường huyết",
  "cường giáp",
  "suy giáp",
  "bướu cổ",
  "rối loạn nội tiết",
  "mãn kinh sớm",
  "rối loạn tiền mãn kinh",
  "hội chứng buồng trứng đa nang",
  "u xơ tử cung",
  "lạc nội mạc tử cung",
  "viêm nhiễm phụ khoa",
  "viêm phần phụ",
  "rối loạn tiền đình",
  "say tàu xe",
  "đau nửa đầu",
  "migraine",
  "thiếu máu não",
  "thiểu năng tuần hoàn não",
  "rối loạn lo âu",
  "rối loạn ám ảnh cưỡng chế",
  "rối loạn lưỡng cực",
  "tâm thần phân liệt",
  "rối loạn ăn uống",
  "chán ăn tâm thần",
  "ăn vô độ",
  "rối loạn hoảng sợ",
  "rối loạn stress sau chấn thương",
  "tự kỷ",
  "tăng động giảm chú ý",
  "rối loạn phát triển",
  "chậm phát triển",
  "khuyết tật học tập",
  "nói ngọng",
  "rối loạn ngôn ngữ",
  "khó nói",
  "tăng huyết áp thai kỳ",
  "tiền sản giật",
  "sản giật",
  "đái tháo đường thai kỳ",
  "dọa sẩy thai",
  "sẩy thai",
  "thai ngoài tử cung",
  "nhau tiền đạo",
  "rau bong non",
  "vỡ ối non",
  "sinh non",
  "thai chết lưu",
  "băng huyết sau sinh",
  "nhiễm trùng hậu sản",
  "tắc tia sữa",
  "áp xe vú",
  "viêm tuyến vú",
  "trầm cảm sau sinh",
  "rối loạn sau sinh",
  "hậu sản mòn",
  "suy dinh dưỡng trẻ em",
  "còi xương",
  "suy giảm miễn dịch",
  "rối loạn chuyển hóa",
  "béo phì trẻ em",
  "chậm nói",
  "tăng động",
  "kén ăn",
  "tiêu chảy cấp ở trẻ em",
  "viêm phổi ở trẻ em",
  "hen suyễn ở trẻ em",
  "viêm phế quản ở trẻ em",
  "sốt siêu vi",
  "nhiễm trùng đường ruột",
  "sán dây",
  "giun sán",
  "bệnh lây truyền qua đường tình dục",
  "giang mai",
  "lậu",
  "sùi mào gà",
  "mụn rộp sinh dục",
  "chlamydia",
  "viêm gan C",
  "viêm gan D",
  "viêm gan E",
  "nhiễm HIV",
  "bệnh AIDS",
  "lao phổi",
  "lao hạch",
  "lao xương khớp",
  "lao màng não",
  "lao ruột",
  "bệnh dại",
  "uốn ván",
  "bạch hầu",
  "ho gà",
  "sởi",
  "cúm gia cầm",
  "cúm heo",
  "MERS",
  "SARS",
  "Zika",
  "Dengue",
  "Chikungunya",
  "sốt xuất huyết",
  "tay chân miệng",
  "viêm não Nhật Bản",
  "viêm não mô cầu",
  "viêm gan virus",
  "sốt vàng da",
  "bệnh do virus",
  "bệnh do vi khuẩn",
  "bệnh do nấm",
  "bệnh do ký sinh trùng",
  "nhiễm trùng bệnh viện",
  "kháng thuốc kháng sinh",
  "dị ứng thuốc",
  "sốc phản vệ",
  "ngộ độc thực phẩm",
  "ngộ độc hóa chất",
  "bỏng",
  "chấn thương",
  "gãy xương",
  "bong gân",
  "trật khớp",
  "rách cơ",
  "đứt dây chằng",
  "tổn thương tủy sống",
  "chấn thương sọ não",
  "chấn thương ngực",
  "chấn thương bụng",
  "vết thương hở",
  "vết thương nhiễm trùng",
  "vết cắn",
  "vết đốt",
  "sốc chấn thương",
  "sốc nhiễm trùng",
  "sốc tim",
  "sốc giảm thể tích",
  "suy hô hấp cấp",
  "suy tuần hoàn cấp",
  "ngừng tim",
  "ngừng thở",
  "hôn mê",
  "mất ý thức",
  "co giật",
  "liệt",
  "mất cảm giác",
  "rối loạn ngôn ngữ",
  "khó nuốt",
  "sặc",
  "tắc nghẽn đường thở",
  "dị vật đường thở",
  "chảy máu trong",
  "xuất huyết não",
  "xuất huyết tiêu hóa",
  "xuất huyết dưới da",
  "thiếu máu cấp",
  "tan máu",
  "thiếu máu do ung thư",
  "thiếu máu do suy thận",
  "thiếu máu hồng cầu nhỏ",
  "thiếu máu hồng cầu to",
  "thiếu máu bất sản",
  "thiếu máu huyết tán",
  "thalassemia",
  "thiếu G6PD",
  "suy tủy",
  "đa hồng cầu",
  "tăng tiểu cầu",
  "giảm tiểu cầu",
  "rối loạn đông máu",
  "Hemophilia",
  "bệnh Von Willebrand",
  "hội chứng đông máu rải rác nội mạch",
  "rối loạn chức năng gan",
  "xơ gan mật nguyên phát",
  "viêm đường mật",
  "tắc đường mật",
  "ung thư đường mật",
  "ung thư tụy",
  "viêm tụy cấp",
  "viêm tụy mãn",
  "nang tụy",
  "đái tháo nhạt",
  "hội chứng Cushing",
  "bệnh Addison",
  "u tuyến yên",
  "u tuyến thượng thận",
  "rối loạn tuyến cận giáp",
  "loãng xương",
  "nhuyễn xương",
  "còi xương",
  "viêm xương khớp",
  "viêm cột sống dính khớp",
  "viêm khớp vảy nến",
  "viêm khớp phản ứng",
  "viêm bao hoạt dịch",
  "viêm gân",
  "viêm cân gan bàn chân",
  "hội chứng ống cổ tay",
  "hội chứng de Quervain",
  "ngón tay lò xo",
  "khối u xương",
  "ung thư xương",
  "sarcoma xương",
  "u sụn",
  "u xương lành tính",
  "rối loạn sắc tố da",
  "nám da",
  "tàn nhang",
  "đồi mồi",
  "bạch biến",
  "lang ben",
  "nấm da",
  "hắc lào",
  "lác đồng tiền",
  "nấm móng",
  "nấm tóc",
  "chốc lở",
  "viêm nang lông",
  "mụn nhọt",
  "rôm sảy",
  "viêm da tiếp xúc",
  "viêm da dị ứng",
  "mề đay mãn tính",
  "phù mạch",
  "ban xuất huyết",
  "nổi mày đay",
  "ung thư da",
  "ung thư tế bào đáy",
  "ung thư tế bào vảy",
  "u hắc tố",
  "u mỡ",
  "u nang bã",
  "sẹo lồi",
  "sẹo phì đại",
  "rạn da",
  "viêm da tiết bã",
  "gàu",
  "rụng tóc hói đầu",
  "rụng tóc từng mảng",
  "viêm da đầu",
  "tóc bạc sớm",
  "tóc khô xơ",
  "mụn trứng cá",
  "mụn bọc",
  "mụn mủ",
  "mụn đầu đen",
  "mụn đầu trắng",
  "viêm da dầu",
  "lỗ chân lông to",
  "da sần sùi",
  "da chảy xệ",
  "nếp nhăn",
  "vết chân chim",
  "quầng thâm mắt",
  "bọng mắt",
  "sụp mí",
  "tăng tiết mồ hôi",
  "mồ hôi trộm",
  "hôi nách",
  "hôi chân",
  "tăng sắc tố da",
  "giảm sắc tố da",
  "rối loạn kinh nguyệt",
  "đau bụng kinh dữ dội",
  "lạc nội mạc tử cung",
  "u nang buồng trứng",
  "đa nang buồng trứng",
  "viêm âm đạo",
  "nhiễm trùng đường tiết niệu",
  "sa tử cung",
  "tiền mãn kinh",
  "mãn kinh",
  "loãng xương sau mãn kinh",
  "bốc hỏa",
  "khô âm đạo",
  "giảm ham muốn tình dục",
  "trầm cảm tiền kinh nguyệt",
  "rối loạn tiền kinh nguyệt",
  "suy buồng trứng sớm",
  "ung thư buồng trứng",
  "ung thư tử cung",
  "ung thư âm đạo",
  "ung thư âm hộ",
  "ung thư vòi trứng",
  "u xơ tuyến vú",
  "nang vú",
  "áp xe vú",
  "viêm tuyến vú",
  "dị tật bẩm sinh",
  "hở hàm ếch",
  "tim bẩm sinh",
  "down",
  "bại não",
  "tự kỷ",
  "chậm nói",
  "chậm đi",
  "chậm phát triển tâm thần vận động",
  "rối loạn tăng động giảm chú ý",
  "rối loạn phổ tự kỷ",
  "chậm phát triển ngôn ngữ",
  "rối loạn học tập",
  "khó đọc",
  "khó viết",
  "khó tính toán",
  "thiếu máu ở trẻ em",
  "suy dinh dưỡng thể thấp còi",
  "suy dinh dưỡng thể gầy còm",
  "suy dinh dưỡng thể phù",
  "tiêu chảy cấp",
  "tiêu chảy kéo dài",
  "viêm họng cấp",
  "viêm amiđan",
  "viêm tai giữa cấp",
  "viêm xoang cấp",
  "viêm kết mạc mắt",
  "viêm giác mạc",
  "đau mắt đỏ",
  "cận thị",
  "viễn thị",
  "loạn thị",
  "nhược thị",
  "tật khúc xạ",
  "glaucoma",
  "đục thủy tinh thể",
  "bệnh lý võng mạc tiểu đường",
  "bong võng mạc",
  "khô mắt",
  "viêm bờ mi",
  "chắp",
  "lẹo",
  "viêm tắc tuyến lệ",
  "viêm mũi dị ứng",
  "polyp mũi",
  "vẹo vách ngăn mũi",
  "chảy máu mũi",
  "nghẹt mũi mãn tính",
  "viêm xoang mãn tính",
  "viêm họng hạt",
  "trào ngược họng thanh quản",
  "khàn tiếng kéo dài",
  "hạt xơ dây thanh",
  "polyp dây thanh",
  "ung thư thanh quản",
  "ung thư vòm họng",
  "ung thư hạ họng",
  "ung thư miệng",
  "ung thư lưỡi",
  "ung thư amidan",
  "ung thư tuyến nước bọt",
  "sâu răng",
  "viêm nướu",
  "viêm nha chu",
  "hôi miệng",
  "chảy máu chân răng",
  "răng khôn mọc lệch",
  "viêm tủy răng",
  "áp xe răng",
  "rụng răng",
  "khó nuốt",
  "nuốt vướng",
  "ợ nóng",
  "ợ chua",
  "đau thượng vị",
  "chán ăn",
  "sụt cân",
  "đầy hơi",
  "buồn nôn",
  "nôn",
  "táo bón",
  "tiêu chảy",
  "phân sống",
  "phân lỏng",
  "phân có máu",
  "phân đen",
  "trĩ",
  "nứt kẽ hậu môn",
  "polyp đại tràng",
  "ung thư đại tràng",
  "ung thư trực tràng",
  "viêm đại tràng mãn tính",
  "hội chứng ruột kích thích",
  "bệnh Crohn",
  "viêm loét đại tràng chảy máu",
  "xuất huyết tiêu hóa trên",
  "xuất huyết tiêu hóa dưới",
  "viêm tụy cấp",
  "viêm tụy mãn tính",
  "sỏi mật",
  "viêm túi mật",
  "ung thư gan",
  "xơ gan",
  "suy gan",
  "viêm gan virus",
  "viêm gan nhiễm mỡ",
  "viêm gan tự miễn",
  "ung thư thực quản",
  "ung thư dạ dày",
  "u trung thất",
  "tràn dịch màng phổi",
  "tràn khí màng phổi",
  "viêm màng phổi",
  "viêm phổi kẽ",
  "xơ phổi",
  "áp xe phổi",
  "lao phổi",
  "ung thư phổi",
  "hen phế quản",
  "bệnh phổi tắc nghẽn mãn tính",
  "giãn phế quản",
  "tăng áp động mạch phổi",
  "suy hô hấp",
  "ngưng thở khi ngủ",
  "ngáy",
  "viêm xoang dị ứng",
  "viêm mũi dị ứng",
  "mày đay mạn tính",
  "phù mạch",
  "sốc phản vệ",
  "dị ứng thực phẩm",
  "dị ứng thuốc",
  "dị ứng côn trùng cắn",
  "viêm da cơ địa",
  "eczema",
  "vảy nến",
  "lupus ban đỏ hệ thống",
  "viêm khớp dạng thấp",
  "gout",
  "viêm cột sống dính khớp",
  "loãng xương",
  "gãy xương",
  "đau vai gáy",
  "đau thần kinh tọa",
  "chấn thương cột sống",
  "hẹp ống sống",
  "trượt đốt sống",
  "gai cột sống",
  "phình động mạch chủ",
  "bóc tách động mạch chủ",
  "hẹp động mạch vành",
  "nhồi máu cơ tim",
  "suy tim",
  "rối loạn nhịp tim",
  "ngoại tâm thu",
  "rung nhĩ",
  "nhịp nhanh kịch phát trên thất",
  "hở van tim",
  "hẹp van tim",
  "viêm nội tâm mạc nhiễm khuẩn",
  "viêm cơ tim",
  "viêm màng ngoài tim",
  "tăng huyết áp",
  "huyết áp thấp",
  "rối loạn lipid máu",
  "xơ vữa động mạch",
  "tai biến mạch máu não",
  "đột quỵ thiếu máu cục bộ",
  "đột quỵ xuất huyết não",
  "xuất huyết dưới nhện",
  "phình mạch não",
  "dị dạng mạch não",
  "thiểu năng tuần hoàn não",
  "hội chứng tiền đình",
  "mất ngủ",
  "rối loạn giấc ngủ",
  "mộng du",
  "ác mộng",
  "ngủ rũ",
  "hội chứng chân không yên",
  "động kinh",
  "Parkinson",
  "Alzheimer",
  "sa sút trí tuệ",
  "bệnh đa xơ cứng",
  "viêm tủy cắt ngang",
  "bệnh nhược cơ",
  "hội chứng Guillain-Barré",
  "bệnh lý thần kinh ngoại biên",
  "đau dây thần kinh sinh ba",
  "liệt Bell",
  "rối loạn lo âu",
  "rối loạn trầm cảm",
  "rối loạn lưỡng cực",
  "rối loạn ám ảnh cưỡng chế",
  "rối loạn hoảng sợ",
  "rối loạn stress sau chấn thương",
  "tâm thần phân liệt",
  "rối loạn nhân cách",
  "rối loạn ăn uống",
  "chán ăn tâm thần",
  "cuồng ăn",
  "rối loạn giấc ngủ",
  "rối loạn hành vi",
  "rối loạn cảm xúc",
  "suy giảm nhận thức",
  "tự kỷ",
  "tăng động giảm chú ý",
  "chậm phát triển",
  "bại não",
  "khuyết tật trí tuệ",
  "hội chứng Down",
  "bệnh di truyền",
  "dị tật bẩm sinh",
  "ung thư",
  "khối u",
  "sinh thiết",
  "hóa trị",
  "xạ trị",
  "phẫu thuật ung thư",
  "tầm soát ung thư",
  "dấu hiệu ung thư",
  "ung thư di căn",
  "ung thư tái phát",
  "ung thư giai đoạn cuối",
  "chăm sóc giảm nhẹ",
  "chăm sóc cuối đời",
  "miễn dịch",
  "hệ miễn dịch",
  "suy giảm miễn dịch",
  "tự miễn",
  "dị ứng",
  "viêm",
  "nhiễm trùng",
  "virus",
  "vi khuẩn",
  "nấm",
  "ký sinh trùng",
  "kháng sinh",
  "kháng virus",
  "kháng nấm",
  "kháng viêm",
  "thuốc ức chế miễn dịch",
  "vắc xin",
  "tiêm chủng mở rộng",
  "tiêm phòng",
  "sức khỏe cộng đồng",
  "dịch tễ học",
  "bệnh truyền nhiễm",
  "ổ dịch",
  "cách ly",
  "khai báo y tế",
  "phòng chống dịch bệnh",
  "an toàn thực phẩm",
  "vệ sinh an toàn thực phẩm",
  "ngộ độc thực phẩm",
  "dinh dưỡng",
  "chế độ ăn",
  "ăn kiêng",
  "béo phì",
  "thiếu cân",
  "suy dinh dưỡng",
  "vitamin",
  "khoáng chất",
  "chất xơ",
  "protein",
  "chất béo",
  "carbohydrate",
  "chất chống oxy hóa",
  "lợi khuẩn",
  "men vi sinh",
  "sức khỏe tinh thần",
  "tâm lý học",
  "trị liệu tâm lý",
  "tham vấn tâm lý",
  "stress",
  "căng thẳng",
  "lo âu",
  "trầm cảm",
  "rối loạn tâm thần",
  "sức khỏe sinh sản",
  "kế hoạch hóa gia đình",
  "mang thai",
  "sinh nở",
  "hậu sản",
  "cho con bú",
  "vô sinh",
  "hiếm muộn",
  "phương pháp tránh thai",
  "bệnh lây truyền qua đường tình dục",
  "tình dục an toàn",
  "sức khỏe trẻ em",
  "phát triển trẻ em",
  "tiêm chủng trẻ em",
  "bệnh trẻ em",
  "dinh dưỡng trẻ em",
  "tăng trưởng trẻ em",
  "bệnh người cao tuổi",
  "lão hóa",
  "chăm sóc người cao tuổi",
  "bệnh mãn tính",
  "phục hồi chức năng",
  "vật lý trị liệu",
  "châm cứu",
  "bấm huyệt",
  "yoga",
  "thiền",
  "thể dục dưỡng sinh",
  "spa",
  "massage",
  "xông hơi",
  "chăm sóc sức khỏe tại nhà",
  "dịch vụ y tế tại nhà",
  "y học từ xa",
  "khám bệnh online",
  "tư vấn sức khỏe trực tuyến",
  "bệnh án điện tử",
  "hồ sơ sức khỏe điện tử",
  "công nghệ y tế",
  "thiết bị y tế",
  "dụng cụ y tế",
  "vật tư y tế",
  "dược phẩm",
  "nghiên cứu y học",
  "thử nghiệm lâm sàng",
  "y học chứng cứ",
  "đạo đức y học",
  "pháp luật y tế",
  "chính sách y tế",
  "bảo hiểm sức khỏe",
  "tài chính y tế",
  "hệ thống y tế",
  "y tế công cộng",
  "y tế tư nhân",
  "bệnh viện đa khoa",
  "bệnh viện chuyên khoa",
  "trạm y tế xã",
  "phòng khám chuyên khoa",
  "phòng khám đa khoa",
  "nhà thuốc",
  "dược sĩ",
  "kỹ thuật viên y tế",
  "điều dưỡng",
  "hộ lý",
  "sinh viên y khoa",
  "giáo sư y học",
  "bác sĩ nội trú",
  "bác sĩ chuyên khoa I",
  "bác sĩ chuyên khoa II",
  "tiến sĩ y học",
  "giáo sư tiến sĩ y học",
  "thầy thuốc ưu tú",
  "thầy thuốc nhân dân",
  "bác sĩ quân y",
  "bác sĩ công an",
  "y sĩ",
  "lương y",
  "bác sĩ y học cổ truyền",
  "thầy thuốc gia truyền",
  "y học dự phòng",
  "sức khỏe nghề nghiệp",
  "an toàn lao động",
  "vệ sinh môi trường",
  "kiểm soát nhiễm khuẩn",
  "khử trùng",
  "tiệt trùng",
  "vô khuẩn",
  "sát khuẩn",
  "nước sạch",
  "không khí sạch",
  "rác thải y tế",
  "xử lý chất thải y tế",
  "an toàn sinh học",
  "phòng thí nghiệm",
  "nghiên cứu khoa học",
  "phát minh y học",
  "cấy ghép nội tạng",
  "ghép tạng",
  "hiến tạng",
  "ngân hàng máu",
  "truyền máu",
  "khẩn cấp",
  "tình trạng nguy kịch",
  "sơ cứu",
  "cấp cứu ngoại viện",
  "cấp cứu nội viện",
  "xe cứu thương",
  "đội ngũ y tế",
  "tình nguyện viên y tế",
  "hỗ trợ y tế",
  "cứu hộ cứu nạn",
  "thảm họa",
  "dịch bệnh",
  "khủng hoảng y tế",
  "biến đổi khí hậu và sức khỏe",
  "an ninh y tế",
  "hệ thống y tế quốc gia",
  "tổ chức y tế thế giới",
  "Bộ Y tế",
  "Sở Y tế",
  "trung tâm kiểm soát bệnh tật",
  "CDC",
  "viện Pasteur",
  "viện vệ sinh dịch tễ",
  "trường đại học y",
  "học viện y học cổ truyền",
  "cao đẳng y tế",
  "trung cấp y tế",
  "chương trình đào tạo y khoa",
  "đào tạo liên tục",
  "cập nhật kiến thức y khoa",
  "hội nghị y học",
  "hội thảo y tế",
  "tạp chí y học",
  "sách y học",
  "tra cứu y khoa",
  "thông tin y tế",
  "hướng dẫn điều trị",
  "phác đồ điều trị",
  "tiêu chuẩn y tế",
  "quy trình khám bệnh",
  "quy định y tế",
  "luật khám chữa bệnh",
  "quy chế bệnh viện",
  "bảng giá dịch vụ y tế",
  "chi phí khám chữa bệnh",
  "hoàn trả bảo hiểm",
  "giải quyết khiếu nại",
  "tư vấn pháp lý y tế",
  "y đức",
  "tinh thần trách nhiệm",
  "thái độ phục vụ",
  "chăm sóc bệnh nhân",
  "quyền lợi bệnh nhân",
  "nghĩa vụ bệnh nhân",
  "sự đồng ý của bệnh nhân",
  "bí mật y tế",
  "bảo mật thông tin",
  "y học cổ truyền",
  "châm cứu",
  "bấm huyệt",
  "thuốc nam",
  "thuốc bắc",
  "cây thuốc nam",
  "bài thuốc dân gian",
  "chữa bệnh bằng đông y",
  "lý thuyết y học cổ truyền",
  "âm dương ngũ hành",
  "khí huyết",
  "tạng phủ",
  "kinh lạc",
  "chẩn đoán đông y",
  "bắt mạch",
  "xem lưỡi",
  "quan sát thần sắc",
  "nghe mùi",
  "hỏi bệnh",
  "điều trị đông y",
  "thang thuốc",
  "viên hoàn",
  "cao",
  "thuốc tễ",
  "xoa bóp",
  "giác hơi",
  "cạo gió",
  "ngâm chân thuốc bắc",
  "xông hơi thảo dược",
  "chế độ ăn dưỡng sinh",
  "dưỡng sinh",
  "tập khí công",
  "thái cực quyền",
  "yoga",
  "thiền",
  "ăn chay",
  "thực dưỡng",
  "thực phẩm chức năng",
  "thực phẩm bổ sung",
  "vitamin tổng hợp",
  "dầu cá omega 3",
  "glucosamine",
  "collagen",
  "sữa non",
  "sữa bột",
  "sữa hạt",
  "tăng cường sức đề kháng",
  "giải độc cơ thể",
  "thanh lọc cơ thể",
  "làm đẹp da",
  "chống lão hóa",
  "giảm cân",
  "tăng cân",
  "tăng cơ",
  "giảm mỡ",
  "chế độ ăn keto",
  "chế độ ăn eat clean",
  "chế độ ăn Địa Trung Hải",
  "ăn chay trường",
  "ăn chay có trứng sữa",
  "ăn chay thực dưỡng",
  "thể hình",
  "cardio",
  "tập tạ",
  "chạy bộ",
  "đạp xe",
  "bơi lội",
  "yoga",
  "thiền",
  "pilates",
  "zumba",
  "aerobics",
  "võ thuật",
  "đấm bốc",
  "bóng đá",
  "bóng rổ",
  "bóng chuyền",
  "tennis",
  "cầu lông",
  "bóng bàn",
  "golf",
  "leo núi",
  "đi bộ đường dài",
  "cắm trại",
  "đạp xe địa hình",
  "thể thao mạo hiểm",
  "phục hồi sau chấn thương",
  "chấn thương thể thao",
  "vật lý trị liệu thể thao",
  "dinh dưỡng thể thao",
  "tâm lý thể thao",
  "sức khỏe tâm thần",
  "tham vấn tâm lý",
  "trị liệu tâm lý",
  "tâm lý học lâm sàng",
  "tâm lý học phát triển",
  "tâm lý học xã hội",
  "stress",
  "lo âu",
  "trầm cảm",
  "rối loạn lo âu",
  "rối loạn hoảng sợ",
  "ám ảnh sợ hãi",
  "rối loạn ám ảnh cưỡng chế",
  "rối loạn căng thẳng sau chấn thương",
  "rối loạn ăn uống",
  "rối loạn giấc ngủ",
  "rối loạn nhân cách",
  "tâm thần phân liệt",
  "rối loạn lưỡng cực",
  "rối loạn giấc ngủ",
  "mất ngủ",
  "khó ngủ",
  "ngủ không sâu giấc",
  "ngủ nhiều",
  "mộng du",
  "ác mộng",
  "ngừng thở khi ngủ",
  "hội chứng chân không yên",
  "rối loạn nhịp sinh học",
  "trầm cảm theo mùa",
  "rối loạn cảm xúc",
  "rối loạn thích ứng",
  "rối loạn phân ly",
  "rối loạn dạng cơ thể",
  "rối loạn giả bệnh",
  "rối loạn phát triển tâm thần",
  "chậm phát triển",
  "khuyết tật trí tuệ",
  "tự kỷ",
  "tăng động giảm chú ý",
  "rối loạn giao tiếp",
  "rối loạn ngôn ngữ",
  "rối loạn lời nói",
  "rối loạn học tập",
  "khó đọc",
  "khó viết",
  "khó tính toán",
  "rối loạn vận động",
  "rối loạn tic",
  "hội chứng Tourette",
  "rối loạn thần kinh phát triển",
  "rối loạn hành vi",
  "rối loạn chống đối",
  "rối loạn cư xử",
  "rối loạn cảm xúc gây rối loạn hành vi",
  "rối loạn nhân cách ranh giới",
  "rối loạn nhân cách chống đối xã hội",
  "rối loạn nhân cách ái kỷ",
  "rối loạn nhân cách phụ thuộc",
  "rối loạn nhân cách tránh né",
  "rối loạn nhân cách ám ảnh cưỡng chế",
  "rối loạn nhân cách dạng phân liệt",
  "rối loạn nhân cách hoang tưởng",
  "rối loạn nhân cách kịch tính",
  "rối loạn nhân cách phân liệt",
  "stress cấp tính",
  "stress mãn tính",
  "kiệt sức",
  "burnout",
  "tự tử",
  "ý định tự tử",
  "cố gắng tự tử",
  "khủng hoảng tâm lý",
  "hỗ trợ tâm lý",
  "điều trị tâm lý",
  "tâm lý trị liệu",
  "nhà tâm lý",
  "chuyên gia tâm lý",
  "bác sĩ tâm thần",
  "dược sĩ tâm thần",
  "liệu pháp nhóm",
  "liệu pháp cá nhân",
  "liệu pháp gia đình",
  "liệu pháp nghệ thuật",
  "liệu pháp âm nhạc",
  "liệu pháp vận động",
  "liệu pháp thư giãn",
  "thiền",
  "yoga",
  "chánh niệm",
  "hít thở sâu",
  "quản lý căng thẳng",
  "quản lý cảm xúc",
  "phát triển bản thân",
  "tự tin",
  "lòng tự trọng",
  "kỹ năng sống",
  "giải quyết vấn đề",
  "giao tiếp hiệu quả",
  "xây dựng mối quan hệ",
  "hạnh phúc",
  "sự hài lòng trong cuộc sống",
  "mục đích sống",
  "giá trị sống",
  "lòng biết ơn",
  "sự tha thứ",
  "lạc quan",
  "hy vọng",
  "sức mạnh nội tâm",
  "khả năng phục hồi",
  "tinh thần tích cực",
  "sức khỏe toàn diện",
  "thân tâm trí",
  "cân bằng cuộc sống",
  "phòng ngừa bệnh tật",
  "chăm sóc sức khỏe chủ động",
  "lối sống xanh",
  "sống khỏe",
  "sống thọ",
  "chất lượng cuộc sống",
  "y tế dự phòng",
  "khám sức khỏe tổng quát",
  "sàng lọc bệnh",
  "tiêm chủng",
  "vệ sinh cá nhân",
  "vệ sinh môi trường",
  "an toàn giao thông",
  "an toàn lao động",
  "phòng cháy chữa cháy",
  "phòng chống thiên tai",
  "sơ cứu ban đầu",
  "cấp cứu ngoại viện",
  "cấp cứu ban đầu",
  "kiểm soát nhiễm khuẩn",
  "chống kháng thuốc",
  "phòng chống dịch bệnh",
  "khai báo y tế",
  "cách ly",
  "giãn cách xã hội",
  "truy vết",
  "xét nghiệm nhanh",
  "xét nghiệm PCR",
  "kháng thể",
  "miễn dịch cộng đồng",
  "biến chủng virus",
  "vắc xin COVID-19",
  "thuốc điều trị COVID-19",
  "hậu COVID-19",
  "phục hồi chức năng sau COVID-19",
  "khám sức khỏe định kỳ",
  "tầm soát ung thư",
  "tầm soát tim mạch",
  "tầm soát tiểu đường",
  "tầm soát huyết áp",
  "tầm soát loãng xương",
  "tầm soát bệnh truyền nhiễm",
  "khám thai định kỳ",
  "siêu âm thai",
  "xét nghiệm sàng lọc trước sinh",
  "xét nghiệm sàng lọc sơ sinh",
  "tiêm chủng cho trẻ",
  "khám sức khỏe trẻ em",
  "tư vấn dinh dưỡng cho trẻ",
  "phát triển thể chất trẻ em",
  "phát triển tinh thần trẻ em",
  "chăm sóc răng miệng",
  "niềng răng",
  "tẩy trắng răng",
  "trồng răng implant",
  "răng sứ",
  "chữa tủy răng",
  "nhổ răng khôn",
  "điều trị viêm nha chu",
  "khám mắt định kỳ",
  "khám tai mũi họng định kỳ",
  "kiểm tra thính lực",
  "kiểm tra thị lực",
  "đo nhãn áp",
  "soi đáy mắt",
  "chụp X-quang phổi",
  "điện tim",
  "siêu âm tim",
  "siêu âm bụng",
  "chụp MRI não",
  "chụp CT cột sống",
  "xét nghiệm máu tổng quát",
  "xét nghiệm nước tiểu",
  "xét nghiệm chức năng gan",
  "xét nghiệm chức năng thận",
  "xét nghiệm mỡ máu",
  "xét nghiệm đường huyết",
  "xét nghiệm hormone",
  "xét nghiệm vi sinh",
  "nuôi cấy",
  "kháng sinh đồ",
  "sinh thiết khối u",
  "phẫu thuật nội soi",
  "phẫu thuật mở",
  "phẫu thuật laser",
  "phẫu thuật thẩm mỹ",
  "phẫu thuật tạo hình",
  "ghép tạng",
  "truyền máu",
  "truyền dịch",
  "điều trị bằng tế bào gốc",
  "liệu pháp gen",
  "y học hạt nhân",
  "y học tái tạo",
  "y học cá thể hóa",
  "y học chính xác",
  "y học từ xa",
  "hệ thống thông tin y tế",
  "bệnh án điện tử",
  "hồ sơ sức khỏe cá nhân",
  "chăm sóc sức khỏe tại nhà",
  "thiết bị y tế thông minh",
  "ứng dụng y tế",
  "robot phẫu thuật",
  "trí tuệ nhân tạo trong y tế",
  "big data y tế",
  "blockchain y tế",
  "công nghệ sinh học",
  "dược liệu",
  "thực phẩm chức năng",
  "tăng cường sức khỏe",
  "chăm sóc sức khỏe cộng đồng",
  "y tế công cộng",
  "chính sách y tế",
  "pháp luật y tế",
  "quyền lợi bệnh nhân",
  "trách nhiệm y tế",
  "y đức",
  "đạo đức y học",
  "nghiên cứu y học",
  "thử nghiệm lâm sàng",
  "y học chứng cứ",
  "phát triển thuốc",
  "nghiên cứu khoa học",
  "giáo dục y tế",
  "đào tạo y khoa",
  "cập nhật kiến thức y khoa",
  "hội nghị y học",
  "tạp chí y học",
  "sách y học",
  "tra cứu y khoa",
  "thông tin y tế",
  "hướng dẫn y tế",
  "khuyến nghị y tế",
  "tư vấn y tế",
  "hỏi đáp sức khỏe",
  "chăm sóc sức khỏe ban đầu",
  "y tế cơ sở",
  "trạm y tế",
  "phòng khám đa khoa",
  "bệnh viện đa khoa",
  "bệnh viện chuyên khoa",
  "phòng cấp cứu",
  "khoa khám bệnh",
  "khoa nội",
  "khoa ngoại",
  "khoa nhi",
  "khoa sản",
  "khoa tim mạch",
  "khoa hô hấp",
  "khoa tiêu hóa",
  "khoa thận tiết niệu",
  "khoa thần kinh",
  "khoa xương khớp",
  "khoa da liễu",
  "khoa mắt",
  "khoa tai mũi họng",
  "khoa răng hàm mặt",
  "khoa ung bướu",
  "khoa truyền nhiễm",
  "khoa hồi sức cấp cứu",
  "khoa xét nghiệm",
  "khoa chẩn đoán hình ảnh",
  "khoa phục hồi chức năng",
  "khoa y học cổ truyền",
  "khoa tâm thần",
  "khoa dinh dưỡng",
  "khoa kiểm soát nhiễm khuẩn",
  "dược sĩ",
  "điều dưỡng",
  "kỹ thuật viên",
  "y tá",
  "hộ lý",
  "bác sĩ chuyên khoa",
  "giáo sư",
  "phó giáo sư",
  "tiến sĩ",
  "thạc sĩ",
  "bác sĩ nội trú",
  "bác sĩ điều trị",
  "trưởng khoa",
  "giám đốc bệnh viện",
  "Bộ Y tế",
  "Sở Y tế",
  "Trung tâm kiểm soát bệnh tật",
  "Viện Pasteur",
  "Viện Vệ sinh dịch tễ",
  "Tổng cục Dân số",
  "Tổng cục Thống kê",
  "Tổng cục Thuế",
  "Cục Quản lý Dược",
  "Cục An toàn thực phẩm",
  "Cục Khám chữa bệnh",
  "Cục Y học cổ truyền",
  "Cục Y tế dự phòng",
  "Cục Quản lý Môi trường Y tế",
  "Cục Khoa học Công nghệ và Đào tạo",
  "Cục Kế hoạch Tài chính",
  "Cục Tổ chức Cán bộ",
  "Thanh tra Bộ Y tế",
  "Vụ Kế hoạch Tài chính",
  "Vụ Pháp chế",
  "Vụ Hợp tác Quốc tế",
  "Vụ Bảo hiểm Y tế",
  "Vụ Sức khỏe Bà mẹ và Trẻ em",
  "Vụ Dân số - Kế hoạch hóa gia đình",
  "Vụ Trang thiết bị và Công trình Y tế",
  "Vụ Khoa học và Đào tạo",
  "Văn phòng Bộ",
  "Tổng cục Dân số",
  "Tổng cục Thống kê",
  "Tổng cục Thuế",
  "Cục Quản lý Dược",
  "Cục An toàn thực phẩm",
  "Cục Khám chữa bệnh",
  "Cục Y học cổ truyền",
  "Cục Y tế dự phòng",
  "Cục Quản lý Môi trường Y tế",
  "Cục Khoa học Công nghệ và Đào tạo",
  "Cục Kế hoạch Tài chính",
  "Cục Tổ chức Cán bộ",
  "Thanh tra Bộ Y tế",
  "Vụ Kế hoạch Tài chính",
  "Vụ Pháp chế",
  "Vụ Hợp tác Quốc tế",
  "Vụ Bảo hiểm Y tế",
  "Vụ Sức khỏe Bà mẹ và Trẻ em",
  "Vụ Dân số - Kế hoạch hóa gia đình",
  "Vụ Trang thiết bị và Công trình Y tế",
  "Vụ Khoa học và Đào tạo",
  "Văn phòng Bộ",
];